from src.algos.greedy_algo import greedy_maximum_non_overlapping_rectangles
from src.algos.random_search_algo import random_search, random_search_for_experiment
from src.algos.genetic_algo import genetic_algorithm
from src.algos.brute_force_algo import brute_force_algo